version: "3.3"

services: 
  blog:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MONGO_HOST=database
      - MONGO_USER=root
      - MONGO_PASS=thenameofjesuschristo
      - MONGO_PORT=27017
      - MONGO_DATABASE=gordon_blog
    links:
      - database
    depends_on:
      - database

  database:
    restart: always
    image: mongo
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: thenameofjesuschristo
    volumes:
      #on monte le volume sur le host du nom de mongo_db
      #a l'enplacement /data/db dans le container.
      - mongo_db:/data/db
  
  mongo-express:
    image: mongo-express
    restart: always
    ports: 
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: thenameofjesuschristo
      ME_CONFIG_MONGODB_SERVER: database
    depends_on:
      - database

volumes:
  mongo_db: