#permet de lancer l'application node avec une configuration
#de mongo db.
#Use : docker-compose up -d

version: "3.8"
services:
  #nom du container
  clean_blog:
    # "fabrique image ici"
    build: .
    ports: 
      - "5000:5000"
    #Variables d'environnement de l'app
    environment: 
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    networks: 
      - gordon

  #service mongo
  mongo:
    image: mongo #télechargée depuis docker hub (via pull)
    restart: on-failure #en cas d'arrêt, on relance.
    #variables d'environnement passées a l'image.
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27018:27017'
    volumes: 
      #on monte le volume persitent crée chez le host
      #en /data/db (du POV du conteneur)
      - mongo_db:/data/db
    #permet de communiquer avec app node.
    networks: 
      - gordon

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - gordon
    

#network a travers lequel les dockers communiquent.
networks:
  gordon: #wallah on a crée un network avec les params par défaut.

volumes:
  mongo_db: #wallah un volume pour la ptite base de données.