version: "3.3"

services: 
  blog:
    build: github.com/swissarthurfreeman/blog
    ports:
      - "4000:4000"
    environment:
      - MONGO_HOST=database
      - MONGO_USER=root
      - MONGO_PASS=thenameofjesuschristo
      - MONGO_PORT=27017
      - MONGO_DATABASE=gordon_blog
    links:
      - database
    volumes:
      #HOST:CONTAINER 
      - .:/usr/src/app
    depends_on:
      - database

  database:
    restart: always
    image: mongo
    volumes:
      - mongo_db:/data/db
  
  mongo-express:
    image: mongo-express
    restart: always
    ports: 
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: thenameofjesuschristo
      ME_CONFIG_MONGODB_SERVER: database

volumes:
  mongo_db: