version: "3.0"

services: 
  blog:
    build: ./
    ports:
      - "4000:4000"
    environment:
      - MONGO_HOST=database
      - MONGO_USER=root
      - MONGO_PASS=thenameofjesuschristo
      - MONGO_PORT=27017
      - MONGO_DATABASE=gordon_blog
    links:
      - database
    volumes:
      #HOST:CONTAINER 
      - .:/usr/src/app
    depends_on:
      - database

  database:
    image: mongo