#this is the file used on raspberry pi.
version: "3.3"

services: 
  blog:
    build: .
    ports:
      - "4000:4000"
    environment:
      #platform deployement is done on specific
      MONGO_HOST: ${MONGO_HOST}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DATABASE: gordon_blog
    restart: on-failure
    depends_on:
      - database
    networks: 
      - blog

  database:
    restart: always
    image: mongo
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      #on monte le volume sur le host du nom de mongo_db
      #a l'enplacement /data/db dans le container.
      - mongo_db:/data/db
    networks:
      - blog
  
  mongo-express:
    image: mongo-express
    restart: always
    ports: 
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_SERVER: database
    depends_on:
      - database
    networks:
      - blog

volumes:
  mongo_db:

networks:
  blog: